// Builds the web version of the app into ../public/app so the CRM server hosts it at
// http://<server>/marketing_crm/app/ (same origin as the API: no CORS needed).
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const out = path.resolve(__dirname, '..', '..', 'public', 'app');
execSync(`npx expo export --platform web --output-dir "${out}" --clear`, { stdio: 'inherit', cwd: path.resolve(__dirname, '..') });

// Single-page app: any /app/... address that is not a real file opens index.html.
fs.writeFileSync(path.join(out, '.htaccess'), [
  '# Generated by mobile/scripts/build-web.js',
  'DirectoryIndex index.html',
  '<IfModule mod_rewrite.c>',
  '    RewriteEngine On',
  '    RewriteCond %{REQUEST_FILENAME} !-f',
  '    RewriteRule ^ index.html [L]',
  '</IfModule>',
  '',
].join('\n'));
console.log('Web app written to ' + out);
